### ISSUE TITLE
mollusk-svm-keys fails to compile with Solana SDK 3.0+ due to removed TransactionAccount type

### ISSUE THREAD

**Issue by skartik-sk** [anza-xyz/mollusk#175]
Description:

mollusk-svm-keys (versions 0.7.1) fails to compile when used with Solana SDK 3.0+ due to an unresolved import.

error[E0432]: unresolved import `solana_transaction_context::TransactionAccount`
 --> mollusk-svm-keys-0.7.1/src/accounts.rs:9:70
  |
9 | solana_transaction_context::{IndexOfAccount, InstructionAccount, TransactionAccount},
  |                                                                  ^^^^^^^^^^^^^^^^^^
  |                                                                  no `TransactionAccount` in the root
  |                                                                  help: a similar name exists: `TransactionAccounts`
